
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library
    password: <Admin!>
    username: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true